### ISSUE TITLE
Local area map TypeError

### ISSUE THREAD

**Issue by JBecquer** [JBecquer/KC-Flying-Club-Plane-Tracker#5]
Traceback (most recent call last):
 line 1892, in __call__
    return self.func(*args)
  File "C:\Users\mrzig\PycharmProjects\KC-Flying-Club-Plane-Tracker\main.py", line 1657, in <lambda>
    command=lambda: graph_aircraft())
  File "C:\Users\mrzig\PycharmProjects\KC-Flying-Club-Plane-Tracker\main.py", line 1366, in graph_aircraft
    local_area_map(sel_aircraft, states_area, sel_month)
  File "C:\Users\mrzig\PycharmProjects\KC-Flying-Club-Plane-Tracker\main.py", line 1061, in local_area_map
    airports_fleet = list(set(airports_N82145 + airports_N4803P))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by JBecquer** [comment]
10/8 Unable to recreate error.

**Comment by JBecquer** [comment]
10/8 Unable to recreate
